version: '3'
services:
  memcached-server:
    image: memcached:latest
    container_name: memcached-server
    environment:
      TZ: Asia/Shanghai
    ports:
      - "11211:11211"
    restart: on-failure
