version: '3'
services:
  halo:
    image: halohub/halo:2.3.0
    container_name: halo-service
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8090:8090"
    restart: on-failure
    volumes:
      - ../data/.halo2:/root/.halo2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness" ]
      interval: 30s
      timeout: 5s
      retries: 5
    command:
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://www.chenyunlong.cn/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=admin
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=4745701816long
